export interface ItemType {
    name: string;
    label: string;
    tip: string;
    type: 'input' | 'number' | 'switch' | 'select' | 'integer';
    options?: { label: string; value: string }[];
    precision?: number;
    step?: number;
    min?: number;
}

export const serverSetting: ItemType[] = [
    {
        name: 'ServerName',
        label: '服务器名称',
        tip: '服务器名称',
        type: 'input',
    },
    {
        name: 'ServerDescription',
        label: '服务器简介',
        tip: '服务器简介',
        type: 'input',
    },
    {
        name: 'ServerPassword',
        label: '服务器密码',
        tip: '服务器密码 (需等待官方更新耐久耐久修复)',
        type: 'input',
    },
    {
        name: 'ServerPlayerMaxNum',
        label: '服务器最大人数',
        tip: '服务器最大人数',
        type: 'integer',
    },
    { name: 'PublicIP', label: '主机位置', tip: '主机位置', type: 'input' },
    {
        name: 'PublicPort',
        label: '主机端口',
        tip: '主机端口',
        type: 'integer',
    },
    {
        name: 'bIsMultiplay',
        label: '多人游戏',
        tip: '默认: False\n未知作用 (True/False)',
        type: 'switch',
    },
    {
        name: 'CoopPlayerMaxNum',
        label: '合作玩家人数',
        tip: '合作玩家人数',
        type: 'integer',
    },
    {
        name: 'AdminPassword',
        label: '管理员密码',
        tip: '服务器管理员密码',
        type: 'input',
    },
    {
        name: 'RCONEnabled',
        label: 'RCON',
        tip: 'RCON 使用或关闭',
        type: 'switch',
        precision: 0,
        step: 1,
        min: 1,
    },
    {
        name: 'RCONPort',
        label: 'RCON 端口',
        tip: 'RCON 端口',
        type: 'integer',
    },
    {
        name: 'Region',
        label: '地区',
        tip: '地区 (目前未知可能后期可以分国家)',
        type: 'input',
    },
    {
        name: 'BanListURL',
        label: '黑名单',
        tip: '封锁名单 (目前来自官方)',
        type: 'input',
    },
];

export const gameSetting: ItemType[] = [
    {
        name: 'Difficulty',
        label: '游戏难度',
        tip: '不影响其他参数调整',
        type: 'select',
        options: [
            { value: 'None', label: '不设置' },
            { value: 'Easy', label: '简单' },
            {
                value: 'Normal',
                label: '普通',
            },
            {
                value: 'Hard',
                label: '困难',
            },
        ],
    },
    {
        name: 'DayTimeSpeedRate',
        label: '白天速度',
        tip: '默认：1\n白天速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'NightTimeSpeedRate',
        label: '夜晚速度',
        tip: '默认：1\n夜晚速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'ExpRate',
        label: '经验倍率',
        tip: '默认：1\n经验倍率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'WorkSpeedRate',
        label: '工作效率',
        tip: '默认：1\n工作效率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerAutoHPRegeneRate',
        label: '玩家生命回复速率',
        tip: '默认：1\n玩家的自动生命回复速率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerAutoHpRegeneRateInSleep',
        label: '玩家睡眠中回复倍率',
        tip: '默认：1\n玩家睡眠中的生命回复倍率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerDamageRateAttack',
        label: '玩家伤害倍率',
        tip: '默认：1\n玩家造成的伤害倍率 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerDamageRateDefense',
        label: '玩家承伤倍率',
        tip: '默认：1\n玩家受到的伤害倍率 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerStaminaDecreaceRate',
        label: '玩家耐力条下降速度',
        tip: '默认：1\n玩家的耐力条下降速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PlayerStomachDecreaceRate',
        label: '玩家饥饿下降速度',
        tip: '默认：1\n玩家的饱足感下降速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalCaptureRate',
        label: '帕鲁抓捕机率',
        tip: '默认：1\n帕鲁抓捕机率 (0.5 - 2)\nPS: 这个参数调整非常敏感请谨慎调整。困难模式为0.8，简单模式为2',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalEggDefaultHatchingTime',
        label: '巨大蛋孵化时间',
        tip: '默认：1(h)\n巨大蛋的孵化时间',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalDamageRateAttack',
        label: '帕鲁伤害倍率',
        tip: '默认：1\n帕鲁造成的伤害倍率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalDamageRateDefense',
        label: '帕鲁承伤倍率',
        tip: '默认：1\n帕鲁受到的伤害倍率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalAutoHPRegeneRate',
        label: '帕鲁生命回复速率',
        tip: '默认：1\n帕鲁的自动生命回复速率',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalAutoHpRegeneRateInSleep',
        label: '帕鲁箱中回复倍率',
        tip: '默认：1\n帕鲁睡眠中的生命回复倍率 (在帕鲁箱中)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalStaminaDecreaceRate',
        label: '帕鲁耐力下降速度',
        tip: '默认：1\n帕鲁的耐力条下降速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalStomachDecreaceRate',
        label: '帕鲁饥饿下降速度',
        tip: '默认：1\n帕鲁的饱足感下降速度 (0.1 - 5)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'PalSpawnNumRate',
        label: '帕鲁的重生数量',
        tip: '默认：1\n帕鲁的重生数量\n若调整为2，王固定变2只，野生帕鲁群2~4只\nPS: 超过3会经常导致帕鲁重叠或掉出地图，请谨慎调整。',
        type: 'number',
        precision: 0,
        step: 1,
        min: 1,
    },
    {
        name: 'DeathPenalty',
        label: '死亡惩罚',
        tip: '死亡惩罚\nNone: 全部不掉落\nItem: 仅掉落道具(不含帕鲁及身上穿的装备武器)\nItemAndEquipment: 除了帕鲁其他全掉\nAll: 帕鲁、装备、道具全部掉落(不包含无法掉落的帕鲁专属装备，如马鞍)',
        type: 'select',
        options: [
            { value: 'None', label: '全部不掉落' },
            { value: 'Item', label: '仅掉落道具(不含帕鲁及身上穿的装备武器)' },
            {
                value: 'ItemAndEquipment',
                label: '除了帕鲁其他全掉',
            },
            {
                value: 'All',
                label: '帕鲁、装备、道具全部掉落(不包含无法掉落的帕鲁专属装备，如马鞍)',
            },
        ],
    },
    {
        name: 'DropItemAliveMaxHours',
        label: '掉落物品的保留时间',
        tip: '默认：1(h)\n掉落物品的保留时间\nPS: 建议设为0.5以保证掉落物不会太多造成卡顿',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'DropItemMaxNum',
        label: '世界内的掉落物上限',
        tip: '世界内的掉落物上限',
        type: 'integer',
    },
    {
        name: 'EnemyDropItemRate',
        label: '敌人掉落倍率',
        tip: '默认：1\n敌人掉落倍率',
        type: 'number',
        precision: 0,
        step: 1,
        min: 1,
    },
    {
        name: 'CollectionDropRate',
        label: '采集资源倍率',
        tip: '默认：1\n采集资源倍率\n例 : 拿石稿敲小帕鲁矿取得1个帕鲁碎片默认要6下平均19点伤害，若调为3则要敲2下平均19点伤害。',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'CollectionObjectHpRate',
        label: '采集资源生命倍率',
        tip: '默认：1\n采集资源生命倍率 (0.5 - 3)\nPS: 经敲小帕鲁矿，测试不生效',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'CollectionObjectRespawnSpeedRate',
        label: '采集资源重生间隔',
        tip: '默认：1\n采集资源重生间隔 (0；0.5 - 3)\nPS: 树木大矿石为1小时，若为0立即重生',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0,
    },
    {
        name: 'BaseCampMaxNum',
        label: '基地最大数量',
        tip: '基地最大数量',
        type: 'integer',
    },
    {
        name: 'BaseCampWorkerMaxNum',
        label: '基地内帕鲁数量',
        tip: '基地内工作帕鲁的最大数量',
        type: 'integer',
    },
    {
        name: 'BuildObjectDamageRate',
        label: '建筑受伤害倍率',
        tip: '默认：1\n建筑受伤害倍率 (0.5 - 3)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0.1,
    },
    {
        name: 'BuildObjectDeteriorationDamageRate',
        label: '建筑劣化速率',
        tip: '默认：1\n建筑劣化速率 (0 - 10)',
        type: 'number',
        precision: 1,
        step: 0.1,
        min: 0,
    },
    {
        name: 'bEnableInvaderEnemy',
        label: '袭击事件',
        tip: '默认: True\n袭击事件关闭开启 (True/False)',
        type: 'switch',
    },
    {
        name: 'bActiveUNKO',
        label: 'UNKO事件',
        tip: '默认：False\n神秘的UNKO事件关闭开启 (True/False)',
        type: 'switch',
    },
    {
        name: 'DropItemMaxNum_UNKO',
        label: 'UNKO掉落物上限',
        tip: '神秘UNKO掉落物上限',
        type: 'integer',
    },
];

export const pvpSetting: ItemType[] = [
    {
        name: 'bIsPvP',
        label: 'PVP模式',
        tip: '默认: False\n[推荐用于PVP] 多人游戏与PVP模式 (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnableNonLoginPenalty',
        label: '登录惩罚',
        tip: '默认：False\n[推荐用于PVP] 登录惩罚 (True/False) [未知作用]',
        type: 'switch',
    },
    {
        name: 'bExistPlayerAfterLogout',
        label: '下线不保护',
        tip: '默认: False\n 玩家登出是否留在原地（不消失） (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnablePlayerToPlayerDamage',
        label: '玩家对玩家伤害',
        tip: '默认: False\n[推荐用于PVP] 玩家对玩家伤害 (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnableFriendlyFire',
        label: '友军伤害',
        tip: '默认: False\n[推荐用于PVP] 玩家对自己帕鲁跟同公会玩家的伤害 (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnableDefenseOtherGuildPlayer',
        label: '其他公会伤害',
        tip: '默认: False\n[推荐用于PVP] 是否受到其他公会伤害 (True/False)',
        type: 'switch',
    },
    {
        name: 'bCanPickupOtherGuildDeathPenaltyDrop',
        label: '捡取其他公会掉落物',
        tip: '默认：False\n[推荐用于PVP] 是否捡取其他公会的死亡掉落物 (True/False)',
        type: 'switch',
    },
];

export const otherSetting: ItemType[] = [
    {
        name: 'bIsStartLocationSelectByMap',
        label: '选择出生点',
        tip: '默认: True\n是否创角后选择出生点 (True/False)\nPS: 若为关则出生在初始台地，死亡后依旧可以选择其他出生点',
        type: 'switch',
    },
    {
        name: 'bEnableFastTravel',
        label: '是否开启快速旅行',
        tip: '默认：True\n是否开启快速旅行 (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnableAimAssistKeyboard',
        label: '键鼠辅助瞄准',
        tip: '默认：False\n键鼠辅助瞄准 (True/False)',
        type: 'switch',
    },
    {
        name: 'bEnableAimAssistPad',
        label: '手把辅助瞄准',
        tip: '默认：False\n手把辅助瞄准 (True/False)',
        type: 'switch',
    },
    {
        name: 'GuildPlayerMaxNum',
        label: '公会人数上限',
        tip: '公会人数上限',
        type: 'integer',
    },
    {
        name: 'bAutoResetGuildNoOnlinePlayers',
        label: '自动退出公会',
        tip: '默认：False\n自动帮玩家退出公会 (True/False)',
        type: 'switch',
    },
    {
        name: 'AutoResetGuildTimeNoOnlinePlayers',
        label: '自动退出工会',
        tip: '默认：72(h)\n自动帮玩家退出公会的时间',
        type: 'number',
        precision: 0,
        step: 1,
        min: 1,
    },
    {
        name: 'bUseAuth',
        label: '是否使用授权',
        tip: '是否使用授权 (作用未知)/nPS: 应该是向官方验证的服务',
        type: 'switch',
    },
];

export const defSetting = {
    Difficulty: 'None',
    DayTimeSpeedRate: 1,
    NightTimeSpeedRate: 1,
    ExpRate: 1,
    PalCaptureRate: 1,
    PalSpawnNumRate: 1,
    PalDamageRateAttack: 1,
    PalDamageRateDefense: 1,
    PlayerDamageRateAttack: 1,
    PlayerDamageRateDefense: 1,
    PlayerStomachDecreaceRate: 1,
    PlayerStaminaDecreaceRate: 1,
    PlayerAutoHPRegeneRate: 1,
    PlayerAutoHpRegeneRateInSleep: 1,
    PalStomachDecreaceRate: 1,
    PalStaminaDecreaceRate: 1,
    PalAutoHPRegeneRate: 1,
    PalAutoHpRegeneRateInSleep: 1,
    BuildObjectDamageRate: 1,
    BuildObjectDeteriorationDamageRate: 1,
    CollectionDropRate: 1,
    CollectionObjectHpRate: 1,
    CollectionObjectRespawnSpeedRate: 1,
    EnemyDropItemRate: 1,
    DeathPenalty: 'All',
    bEnablePlayerToPlayerDamage: 'False',
    bEnableFriendlyFire: 'False',
    bEnableInvaderEnemy: 'True',
    bActiveUNKO: 'False',
    bEnableAimAssistPad: 'True',
    bEnableAimAssistKeyboard: 'False',
    DropItemMaxNum: 3000,
    DropItemMaxNum_UNKO: 100,
    BaseCampMaxNum: 128,
    BaseCampWorkerMaxNum: 15,
    DropItemAliveMaxHours: 1,
    bAutoResetGuildNoOnlinePlayers: 'False',
    AutoResetGuildTimeNoOnlinePlayers: 72,
    GuildPlayerMaxNum: 20,
    PalEggDefaultHatchingTime: 72,
    WorkSpeedRate: 1,
    bIsMultiplay: 'False',
    bIsPvP: 'False',
    bCanPickupOtherGuildDeathPenaltyDrop: 'False',
    bEnableNonLoginPenalty: 'True',
    bEnableFastTravel: 'True',
    bIsStartLocationSelectByMap: 'True',
    bExistPlayerAfterLogout: 'False',
    bEnableDefenseOtherGuildPlayer: 'False',
    CoopPlayerMaxNum: 4,
    ServerPlayerMaxNum: 32,
    ServerName: 'Default Palworld Server',
    ServerDescription: '',
    AdminPassword: '',
    ServerPassword: '',
    PublicPort: 8211,
    PublicIP: '',
    RCONEnabled: 'False',
    RCONPort: 25575,
    Region: '',
    bUseAuth: 'True',
    BanListURL: 'https://api.palworldgame.com/api/banlist.txt',
};
